# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== ELKOM 1 ==========\n')
def list_to_tuple(input_list):
    try:
        result_tuple = tuple(input_list)
        return result_tuple
    except Exception as e:
        return f"Error: {e}"

input_list = [1, 2, 3, 4, 5]
result_tuple = list_to_tuple(input_list)

print(input_list)
print('hasil reverse ke tuple')
print(result_tuple)

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== ELKOM 2 ==========\n')
a = ('3212, 1782, 4354', '4534, 1026, 1021', '1022, 1037, 1030')
print(a)
def ratarata(angka):
    rata_rata = [int(x) for x in angka.split(', ')]
    return int(sum(rata_rata) / len(rata_rata))

averages = [ratarata(group) for group in a]
print("rata rata dari tuple adalah : ")
print(averages)

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== ELKOM 3 ==========\n')
def calculate_product(input_list):
    result_product = 1
    for value in input_list:
        result_product *= value

    return result_product

input_list = [2, 3, 4, 5]
result_product = calculate_product(input_list)

print(input_list)
print(result_product)

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== ELKOM 4 ==========\n')
def hitung_string_cocok(list_string):
    jumlah_cocok = 0

    for string in list_string:
        if len(string) >= 2 and string[0] == string[-1]:
            jumlah_cocok += 1
    return jumlah_cocok


daftar_string = ['bang gaga ganteng', 'dan', 'bang natan cool', 'gantengg']
jumlah = hitung_string_cocok(daftar_string)
print("list kata:",daftar_string)
print(f"Jumlah string dengan karakter pertama dan terakhir sama adalah: {jumlah}")